apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attest-vec
spec:
  validationFailureAction: audit
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: check-vex
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "ghcr.io/jimbugwadia/demo-java-tomcat:*"
        key: |-
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHMmDjK65krAyDaGaeyWNzgvIu155
          JI50B2vezCw8+3CVeE0lJTL5dbL3OP98Za0oAEBJcOxky8Riy/XcmfKZbw==
          -----END PUBLIC KEY-----     
        attestations:
          - predicateType: https://cyclonedx.org/BOM
            conditions:
              - all:
                # vulnerabilities with a score higher than 8.0, must be 0
                - key: "{{ vulnerabilities[].ratings[?score >= `8.0`][] | length(@) }}"
                  operator: Equals
                  value: 0
